### ISSUE TITLE
Test library

### ISSUE THREAD

**Issue by snikolayev** [NRules/NRules#103]
Create a library (and publish it via nuget) to allow easy authoring of rule unit tests.
The library should only depend on NRules and not any particular test runner or assertion framework.

**Comment by domingoladron** [comment]
I'd be very keen for this.  I love NRules, and have used it in a number of projects.  Having a unit test hook into individual rules would be amazing.

**Comment by snikolayev** [comment]
@coactivechris the idea is to create a new library, say NRules.Test, that would allow anyone to build unit tests very similar to NRules.IntegrationTests (I would in fact use existing integration tests as inspiration/starting point).
If you want to take a stab at this, I can help you.

**Comment by domingoladron** [comment]
@snikolayev,

Let me have a look at the integration tests, see how you've structured it, etc.

With most of the unit testing I've done as of late, the style would be along the lines of using IoC (via interfaces) to make it possible to test rules.

Were you imagining testing the rules individually, or as a collective whole inside the network?

**Comment by snikolayev** [comment]
Integration tests test individual rules or a very small number of directly related rules, but the rules are still loaded inside the network. You then insert/update/retract facts and assert whether the rule(s) fired or not and which facts matched.
You don't necessarily need a container, and can either use a default rule activator, or provide a way for the user to instantiate the rule class by hand, so that the user can inject the dependencies (if any) manually. If the user chooses to use an IoC container though, they should be able to.
An overarching concern I'm thinking about is the dependencies, to ideally not tie this to any unit testing, mocking, assertion framework, or a specific IoC container. As I imagine different people use different ones, and should still be able to get the benefit of this library.
Take a look and see what you think.
