### ISSUE TITLE
Claims Adjudication

### ISSUE THREAD

**Issue by anerhyvo** [NRules/NRules#125]
Is there a bug in ClaimsExpert.Rules -> StatusRules? 
Should:
.Do(ctx => Approve(claim));
be: 
.Do(ctx => ctx.Update(Approve(claim)));

**Comment by snikolayev** [comment]
@anerhyvo 
Technically, yes, these rules must update the fact in the rules engine after modifying it. Practically, nothing forward chains on claim status, so it doesn't matter; - except when the claim is denied; but the deny rule looks like this:
```c#
            Then()
                .Do(ctx => Deny(claim))
                .Do(ctx => ctx.Update(claim));
```

To be absolutely correct, all StatusRules should do this (or the single-line form of it, like you described).
If you like, you can fix it and send a pull request.

**Comment by snikolayev** [comment]
If anyone cares to fix this in the samples, you can reopen and send a PR
