### ISSUE TITLE
NRules Autofac integration package does not support Autofac 3.3.1 and higher

### ISSUE THREAD

**Issue by nagoh** [NRules/NRules#137]
Taking from the example @ https://github.com/NRules/NRules/wiki/Rule-Dependencies (i.e. using NRules.Integration.Autofac) I keep getting an exception with the following code:

```
 var types = containerBuilder.RegisterRules(x => x.AssemblyOf(typeof(IMyRule)));
 containerBuilder.RegisterRepository(r => r.Load(x => x.From(types)));
 containerBuilder.RegisterSessionFactory();
 containerBuilder.RegisterSession();
```

System.MissingMethodException : Method not found: 'Autofac.Builder.IRegistrationBuilder`3<!0,!1,!2> Autofac.Builder.IRegistrationBuilder`3.PropertiesAutowired(Autofac.PropertyWiringOptions)'.
   at NRules.Integration.Autofac.RegistrationExtensions.RegisterRepository(ContainerBuilder builder, Action`1 initAction)

Any thoughts?

**Comment by snikolayev** [comment]
Hi @nagoh
What version of Autofac do you have installed in the solution?

**Comment by nagoh** [comment]
~0.8.0~

Sorry Autofac = 4.4.0

**Comment by snikolayev** [comment]
That's the version of NRules and the integration package; I meant the version of the Autofac itself. According to this (https://github.com/autofac/Autofac/issues/520) they moved the method in Autofac. I just want to be sure that's the problem.

**Comment by snikolayev** [comment]
Oh, just saw your update - I'll take a look, but it does seem like what I mentioned in my comment above. If that's the case, a quick work around on your side could be to locally re-compile NRules.Integration.Autofac with the version of Autofac that you want to use.

**Comment by snikolayev** [comment]
This will be addressed in 0.8.1 release (upgrading references to Autofac 3.3.1, which is compatible with 4.4.0)

**Comment by sergiuciudin** [comment]
Still getting this exception in Autofac 4.9.4

**Comment by dkamau** [comment]
@tuzik12 did you get a workaround for the error? Getting the same with autofac 5.1.3 @snikolayev any tips?

**Comment by snikolayev** [comment]
@tuzik12 Autofac had some breaking changes, so the Autofac integration code needs to be recompiled against the new version. For now, until the new NRules release is out, I recommend that you recompile it yourself against the version of Autofac that you are using in your project.
