### ISSUE TITLE
rule dependency example

### ISSUE THREAD

**Issue by sk8tz** [NRules/NRules#141]
Can you provide an example of how I can achieve the following

lets say I have these Rules: rule1, rule2, rule3, rule4, rule5, rule6

rule4 is dependent on rule3
rule3 is dependent on rule2
rule2 is dependent on rule1

rule5 is dependent on rule2

So basically I want to write something like this with no order of precedence

[Rule("RuleX")]
When
           rule2.IsSuccess && rule3.IsSuccess && rule4.IsSuccess
Then
          ctx.DoSomething()

[Rule("RuleY")]
When
           rule5.IsSuccess && RuleX.IsSuccessfull
Then
          ctx.DoSomethingElse()

Is this possible to walk the Rules AST and dependencies, and its evaluations. Can I see an example ?

**Comment by snikolayev** [comment]
@sk8tz NRules is an inference engine, this means the engine determines the order of the rules execution based on available data (facts). There is no concept of rules depending on other rules. The rules depend on data/facts (it is said that rules match facts); and whichever rules matched the facts they get executed. If multiple rules matched facts at the same time, the rule with higher priority gets executed first. If priorities are the same, the order is unspecified.

Can you please elaborate on what you mean by rule.IsSuccess? And I don't understand the question about walking the AST for dependencies and evaluations.

To better understand how rules engines work, I would recommend this article: 
* https://www.sparklinglogic.com/rete-algorithm-demystified-part-1/
* https://www.sparklinglogic.com/rete-algorithm-demystified-part-2/
* https://www.sparklinglogic.com/rete-algorithm-demystified-part-3/
