### ISSUE TITLE
Generic DSL extensions, compilation error

### ISSUE THREAD

**Issue by ThaBaer** [NRules/NRules#142]
Hi,

I'm trying to write a generic DSL extension method. Unfortunately compiling a rule that uses it results in a NotImplementedException in ExpressionComparer.MemberExpressionsEqual:
`System.NotImplementedException : Convert(fact, IFactType1).Name`

Here's a small sample that triggers the exception. Unfortunately I wasn't able to debug into it any deeper.    

    public interface IFactType1
    {
        string Name { get; }
    }

    public interface IFactType2 : IFactType1
    {
    }

    public static class MemberExpressionEqualTestExtensions
    {
        public static ILeftHandSideExpression MatchFactType<TFact>(this ILeftHandSideExpression lhs, Expression<Func<TFact>> alias, string name, params Expression<Func<TFact, bool>>[] conditions) where TFact : IFactType1
        {
            return lhs.Match<TFact>(alias, f => f.Name.Equals(name));
        }
    }

    public class MemberExpressionEqualTestRule : Rule
    {
        public override void Define()
        {
            IFactType2 fact = null;
            IFactType2 fact2 = null;

            When()
                .MatchFactType(() => fact, "foo")
                .MatchFactType(() => fact2, "bar");

            Then()
                .Do(ctx => ctx.Halt());
        }
    }

Maybe you can take a look.
Many thanks!

**Comment by snikolayev** [comment]
It appears, due to the generic type constraint, compiler inserts a type conversion to the expression tree, which is not supported by the expression comparer (which NRules uses to determine if expressions are equivalent or not, so that it can share nodes in the Rete graph for equivalent expressions). I'll fix.

**Comment by ThaBaer** [comment]
Great, thanks.
