### ISSUE TITLE
Stop update propagation of linked facts

### ISSUE THREAD

**Issue by ThaBaer** [NRules/NRules#145]
Hi Sergiy,

here's an idea. I'd like to stop update propagation of linked facts if the update does not change the linked facts.

E.g. there's an integer fact and a rule that creates a linked fact if the parent fact < 5. The presence of the linked fact simply signifies the value is below the threshold 5.
Insert 4 -> Fire -> Linked fact created
Update to 3 -> Fire -> linked fact unchanged, because the linked fact is not dependent on the exact value.

What do you think?

**Comment by snikolayev** [comment]
That's what agenda filters were designed for (see [here](https://github.com/NRules/NRules/wiki/Agenda-Filters#fluent-rule-filters)). Let me know if this is what you were looking for.
```c#
MyFact fact = null;
When()
    .Match(() => fact, x => x.Value < 5);

Filter()
    .OnChange(() => fact.Value < 5);

Then()
    .Yield(ctx => new LessThanFive()); 
```
In this case, your condition and filter are the same, but this supports other scenarios too.
Also, if you only want the rule to fire once, and not on updates, you can just mark the rule as [non-repeatable](http://nrules.net/api/html/T_NRules_RuleModel_RuleRepeatability.htm).

**Comment by ThaBaer** [comment]
Ah, I wasn't aware you could do that. I thought the expressions were simply meant to define the properties to monitor, similar to the alias expressions.

Yes, that works nicely. Thanks!
