### ISSUE TITLE
Getting exception of 'System.OutOfMemoryException'.

### ISSUE THREAD

**Issue by Sabyasachisamaddar** [NRules/NRules#148]
I have created a c# project with 2000 records (A ,B) and in the rules I am comparing each A with all the B's.
It worked for me with 1000 records (11 secs) but with 2000 records it is showing  'System.OutOfMemoryException'

**Comment by snikolayev** [comment]
Can you please attach the failing rule or some repro code?

**Comment by Sabyasachisamaddar** [comment]
The Rule ...................................................................
 public class EqualityRule : Rule
    {
        public override void Define()
        {
            MasterDB mdb = null;
            IEnumerable<StagingDB> sdb = null;            

            When()
                .Match<MasterDB>(() => mdb)
                .Query(() => sdb, x => x
                .Match<StagingDB>(
                    o => o.ID == mdb.ID,
                    o => o.rawMarks == mdb.rawMarks,
                    o => o.Grade == mdb.Grade)
                .Collect()
                .Where(c => c.Any()));
                
            Then()
                .Do(ctx => Action(mdb.ID));
            
                
        }

        public static void Action(int id)
        {
            Console.WriteLine(id + "---------Exception 10" );
        }
    }

---------------------------------------------------------

code to call the rule :

var repository = new RuleRepository();
            repository.Load(x => x.From(typeof(EqualityRule).Assembly));
            var factory = repository.Compile();
            var session = factory.CreateSession();

            List<StagingDB> sdb = new List<StagingDB>();
            var mdb = new List<MasterDB>();

            for (int i=0; i<2000; i++)
            {
                sdb.Add(new StagingDB(1, 88, "A"));
                mdb.Add(new MasterDB(1, 88, "A"));                
            }

            session.InsertAll(sdb);
            session.InsertAll(mdb);
            session.Fire();

**Comment by snikolayev** [comment]
I tried under .NET Framework 4.6.2 and .NET Core 2.0, 32 bit and 64 bit, and I cannot see any issues (besides the fact that you are inserting all objects with the same IDs). Below is the code I was running. 
Is this the same code you ran? What's your definition of StagingDb and MasterDb?

P.S. Are you trying to use NRules as an ETL tool?

```c#
    internal class Program
    {
        private static void Main(string[] args)
        {
            var repository = new RuleRepository();
            repository.Load(x => x.From(typeof(EqualityRule).Assembly));
            var factory = repository.Compile();
            var session = factory.CreateSession();

            var sdb = new List<StagingDb>();
            var mdb = new List<MasterDb>();

            for (var i = 0; i < 2000; i++)
            {
                sdb.Add(new StagingDb(1, 88, "A"));
                mdb.Add(new MasterDb(1, 88, "A"));
            }

            session.InsertAll(sdb);
            session.InsertAll(mdb);
            session.Fire();
        }
    }

    public class StagingDb
    {
        public StagingDb(int id, int rawMarks, string grade)
        {
            Id = id;
            RawMarks = rawMarks;
            Grade = grade;
        }

        public int Id { get; }
        public int RawMarks { get; }
        public string Grade { get; }
    }

    public class MasterDb
    {
        public MasterDb(int id, int rawMarks, string grade)
        {
            Id = id;
            RawMarks = rawMarks;
            Grade = grade;
        }

        public int Id { get; }
        public int RawMarks { get; }
        public string Grade { get; }
    }

    public class EqualityRule : Rule
    {
        public override void Define()
        {
            MasterDb mdb = null;
            IEnumerable<StagingDb> sdb = null;

            When()
                .Match(() => mdb)
                .Query(() => sdb, x => x
                    .Match<StagingDb>(
                        o => o.Id == mdb.Id,
                        o => o.RawMarks == mdb.RawMarks,
                        o => o.Grade == mdb.Grade)
                    .Collect()
                    .Where(c => c.Any()));

            Then()
                .Do(ctx => Action(mdb.Id, sdb));
        }

        private static void Action(int id, IEnumerable<StagingDb> sdb)
        {
            Console.WriteLine($"{id} {sdb.Count()}");
        }
    }
```

**Comment by Sabyasachisamaddar** [comment]
I am really sorry, I gave the wrong rule

public class MarksMoreThanZeroRule : Rule
    {
        public override void Define()
        {
            MasterDB mdb = null;
            IEnumerable<StagingDB> sdb = null;

            When()
                .Match<MasterDB>(() => mdb)
                .Query(() => sdb, x => x
                .Match<StagingDB>(
                    o => o.ID == mdb.ID,
                    o => o.rawMarks > 0)

                .Collect()
                .Where(c => c.Any()));

            Then()
                .Do(ctx => Action(mdb.ID));

        }

        public static void Action(int id)
        {
            Console.WriteLine(id + "---------Exception 14");
        }
    }

Please make the count 3000 now, I was running both the rules with 2000 and it was crashing.

**Comment by snikolayev** [comment]
Thank you. I reproduced it with the new rule and the 32 bit process. I'll investigate

**Comment by snikolayev** [comment]
A quick follow-up on this. The rule joins MasterDB and StagingDB objects on ID (among other conditions). Given that all IDs are the same, this creates a Cartesian Product, that's 9 million intermediate objects. That, combined with the fact that Rete algorithm sacrifices space for performance (keeps partial matches in memory), creates huge memory footprint.
I'm still looking at ways to shave off some memory usage where possible, but ultimately - Rete algorithm is not suitable for generating Cartesian Products of facts.

Generating facts using the following code (setting ID to i, instead of 1) makes the match very fast and not use much memory, since there is no Cartesian Product:
```c#
for (var i = 0; i < 3000; i++)
{
    sdb.Add(new StagingDb(i, 88, "A"));
    mdb.Add(new MasterDb(i, 88, "A"));
}
```
