### ISSUE TITLE
YieldMany

### ISSUE THREAD

**Issue by linanqiu** [NRules/NRules#155]
```csharp
// manyThings is IEnumerable<object>
Then()
    .YieldMany(_ => manyThings);
```

links each of the objects in `manyThings` to the activation and manages keys / linking in the background.

**Comment by linanqiu** [comment]
I'm working on this

**Comment by snikolayev** [comment]
How are you planning to match yielded objects with the linked facts during the update?

**Comment by linanqiu** [comment]
Yeah realized that's the hard part.

Alternatively, it should easier to keep the bijection between activations and linked facts. What we need is a more flexible GroupBy that doesn't depend on matching particular facts. See PR for proposed fix.
