### ISSUE TITLE
Does NRules support visualization/export of rule flow?

### ISSUE THREAD

**Issue by bremnes** [NRules/NRules#164]
Perhaps it goes against the nature of a inference engine, but I have to ask. Is there any way to visualize the rule flow? For instance something similar to a bpmn user interface?

The reason why I'm asking is that if we use NRules, then it seems like the rules are only available to us developers. I'd like to visualize this somehow so that more functional roles can also understand what's the currently implemented/active rule flow.

Thanks!

**Comment by snikolayev** [comment]
@bremnes this is a great question. There is no readily available visualizer or something like that, but the information is there for you to collect and visualize as needed.
First, it's important to note that the rule flow in an inference engine is the product of the rules firing on specific facts, and is not a product of the static rules structure. In other words, different facts will lead to different rule flows. Therefore, to deduce the rule flow you would need to run your scenarios through the engine and capture the runtime information.

There are a few ways you could collect runtime information in NRules:
* Attach event handlers to the session (see [ISession.Events](http://nrules.net/api/html/P_NRules_ISession_Events.htm), [RuleFiredEvent](http://nrules.net/api/html/E_NRules_Diagnostics_IEventProvider_RuleFiredEvent.htm) and [Diagnostics](https://github.com/NRules/NRules/wiki/Diagnostics#execution-event-model))
* Implement an [ActionInterceptor](http://nrules.net/api/html/T_NRules_Extensibility_IActionInterceptor.htm)

In either case, your application will get control whenever a rule fires, giving you access to the `RuleDefinition` of the rule that fired, and the facts it matched. So, you can collect this information and visualize it in a way suitable for your application.
