### ISSUE TITLE
Documentation for Right Hand Side

### ISSUE THREAD

**Issue by DonaldAirey** [NRules/NRules#165]
There appears to be sufficient documentation to understand the rule evaluation, but, unless I'm missing something obvious, I can't find any documentation about what to do once you've made a match?  For example, in the DSL Extensions page, there's an example where a warning system is called (similar to what I want to do).  I see that the input to the _Do_ function is an IContext object, but I don't see in the example of that page how the **ContextExtensions** is injected into the rule.  The class doesn't seem to inherit from **IContext**, so I'm lost as to how this can be called from the _Do_ function.  Some information and illustrations on this subject would be very helpful.  Thanks.

**Comment by snikolayev** [comment]
This is also answered on the [forum](https://groups.google.com/forum/#!topic/nrules-users/QPRdeEJgOk0).

@GammaFour The `Do` clause simply accepts an action delegate that's called every time the rule fires. The rule action can either update the facts it matched, perform some calculation, insert new facts, etc. The rule action interacts with the rules engine via the IContext argument. The action can also interact with the hosting application via injected services (see [rule activation](https://github.com/NRules/NRules/wiki/Fluent-Rules-Loading#rule-activation)).
One can also define extension methods (like in the [DSL extensions](https://github.com/NRules/NRules/wiki/DSL-Extensions) example), to improve rule's readability. But ultimately that's just a syntactical sugar over the Do method. These are just regular [extension methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods), like the `ContextExtensions` example.

**Comment by snikolayev** [comment]
I'm closing this issue. If you have further questions, please ask on the user group or gitter forum.
