### ISSUE TITLE
Node sharing depends on order of conditions being added

### ISSUE THREAD

**Issue by a046** [NRules/NRules#167]
I was playing around with the visualiser and debugging the creation of the RETE network in NRules and noticed some odd behaviour with node sharing not occurring when I would expect it to.

As the alpha nodes are created from the conditions iteratively and sharing occurs when the "currentAlphaNode" already has that condition as a child, if multiple rules share some conditions but have them in another order or a similar variation from each other there will be no node sharing - sharing only occurs where the pattern from the start of the left hand side is identical.

Is this a bug? Do other RETE implementations handle this?

**Comment by snikolayev** [comment]
@a046 you are correct, that's how it works. It is actually very subtle, as there are two competing forces - node selectivity and node sharing. So, imagine there are two patterns with identical conditions C1 and C2, but one pattern has them reversed. Should we share the nodes and have them flow in C1,C2 order or C2,C1 order? Now imagine C1 filters out 90% of facts and C2 filters out 10% of facts - clearly, the order could matter.
Not sure what other engines do in these cases.
This is getting into the area of topology optimizations, and I'm not sure I want to tackle that right now.
One thing I'm thinking about is a VS plugin that can analyze the rules as you are writing them and highlight these optimization opportunities, but ultimately let the rules writer decide.
Nevertheless, I'll keep this issue open, as I agree this has to be solved one way or the other.

**Comment by a046** [comment]
That makes a lot of sense, I thought about this a bit after posting too. Seems to have a lot in common with index selection in a RDBMS.

Page 10 (pdf page 24) of Doorenbos seems to show the same behaviour, so I am guessing it is standard: http://reports-archive.adm.cs.cmu.edu/anon/1995/CMU-CS-95-113.pdf
