### ISSUE TITLE
Add Rules without Redeployment

### ISSUE THREAD

**Issue by vikasNew** [NRules/NRules#172]
Hi,

Is that possible to manage rules in xml files & we don't need to redeploy my application when i add/edit any rule in xml file.

is that possible with NRules ?

**Comment by a046** [comment]
Yes, but you'd need to use Canonical Model to define the rules and create your own way of serialising/deserialising the rules I believe. See https://github.com/NRules/NRules/wiki/Rule-Builder

The experimental rule language might be of interest to you, not sure how far along it is though: https://github.com/NRules/NRules.Language
