### ISSUE TITLE
How to select list object by comparing another with NRules?

### ISSUE THREAD

**Issue by amolnak** [NRules/NRules#190]
We have to select data which in the list by comparing another list object but we are able to the same

we have send one object at time which are looping through all the data which leads to an performance issue so can anyone please help us on the same.

      foreach (DataRow row in DtProc.Tables[0].Rows)
        {
            objClassModelProc.ACCOUNT_NUM = row["ACCOUNT_NUM"].ToString();
            objClassModelProc.PX = row["CODE"].ToString();
            objClassModelProc.CodeClass = row["CODE_CLASS"].ToString();
            objClassModelProc.SpecialityName = row["SpecialityName"].ToString();
            lstClassModelProc.Add(objClassModelProc);
            var ClassModelProcList = new List<ClassModelProc>();
            ClassModelProcList = lstClassModelProc;

            var repositoryDenominator = new RuleRepository();
            repositoryDenominator.Load(x => x.From(typeof(PreferredRuleDenominator).Assembly));
            var factoryDenominator = repositoryDenominator.Compile();
            var sessionDenominator = factoryDenominator.CreateSession();
            sessionDenominator.Insert(objClassModelProc);
            sessionDenominator.Fire();
        }
        PushDATAINTOMAINTABLE(DtProc.Tables[0].Rows.Count, "Final");

NRule

        IEnumerable<ClassModelProc> classModelProc = null;
        //ClassModelDenominator objClassModelDenominator = null;
        GetMaster(DtSet, "REGetMaster");
        System.Data.DataTable dt = DtSet.Tables[0];
        List<string> list = dt.Rows.OfType<System.Data.DataRow>().Select(dr => (string)dr["Denominator"]).ToList();
        List<string> CodeClass = new List<string> { "CPT4", "HCPC4" };
        When()
          .Query(() => classModelProc, x => x
          .Match<ClassModelProc>(
            o => list.Contains(o.PX)
            , o => CodeClass.Contains(o.CodeClass)
            )
          .Collect());

        Then()
            .Do(ctx => SetCount(classModelProc, "Denominator"));

**Comment by snikolayev** [comment]
You can put the items you are looking up against in a HashSet, instead of a list.

Closing this, and moving forward, please ask questions on the forum or gitter chat, and reserve issues for bug reports and feature requests.
