### ISSUE TITLE
How to install nrules debug visualizer?

### ISSUE THREAD

**Issue by Lufleda** [NRules/NRules#194]
Hello, I'm a programming freshman. Can someone tell me more about how to get the debug visualizer to work? Which file exactly do I have to build? Unfortunately, I only get error messages when I execute the debug visualizer executable file. 

Thank you !

**Comment by snikolayev** [comment]
NRules 0.9.2 release fixed a host of issues with the debugger visualizer. It now supports VS 2019 and can be used with any client code compatible with .NET Standard 2.0. Wiki documentation was updated with the deployment and usage information: https://github.com/NRules/NRules/wiki/Diagnostics#debugger-visualizer
