### ISSUE TITLE
Is there a way to run NRule Engine in asyncronously?

### ISSUE THREAD

**Issue by RockStar201** [NRules/NRules#195]
Can i make call as below:

session.FireAsync();

**Comment by nicktyrrell** [comment]
The creator has said explicitly that they do not plan on implementing asynchronous functionality (https://github.com/NRules/NRules/issues/186). As such, you would be best placed to do all heavy lifting outside of the rules engine.

**Comment by snikolayev** [comment]
@nicktyrrell is correct.
NRules session is inherently single-threaded and rules execution is synchronous. You are obviously free to spin up a Task or something and fire rules there, as long as you ensure single-threaded access to the session object.

**Comment by RockStar201** [comment]
@snikolayev @nicktyrrell Thanks for the update.
I need help regarding this https://stackoverflow.com/questions/57722215
