### ISSUE TITLE
Using OR-statement in .RUL file

### ISSUE THREAD

**Issue by TristanHam123** [NRules/NRules#197]
I'm trying to do more complex logic in the .rul file and I don't see any documentation explaining OR-statements and I've tried a few things by trial-and-error and none are working. Could you write out a simple example that uses an OR-statement in the .RUL file, please?

**Comment by snikolayev** [comment]
I'm closing this issue. This is the wrong repository for issues with Rule# language. I also see that the same issue is created in the correct repo.
