### ISSUE TITLE
WeightCalculationRule doesn't seem to Match subquery

### ISSUE THREAD

**Issue by NicoJuicy** [NRules/NRules#199]
The following rules has no OrderLines, although:

100% sure that Product.RequireShipping = true everywhere
100% sure that every product has a weight

    [Priority(100)]
    [Tag("Shipping")]
    public class WeightCalculationRule : Rule
    {
        public override void Define()
        {
            Shop.Models.Order order = null;
            IEnumerable<OrderLine> orderlines = null;
            double totalWeight = 0.0;

            When()
                .Match(() => order)
                .Query(() => orderlines, ol => ol
                    .Match<OrderLine>(o =>
                        o.Product.Weight.HasValue,
                        o => o.Product.requireShipping)
                    .Collect())
                .Let(() => totalWeight, () => orderlines.Sum(ol => ol.Amount * ol.Product.Weight.Value * (double)ol.Product.WeightOption) / 1000.0) //For kg
                .Having(() => totalWeight > 0);

            Then()
                .Do(ctx => ApplyWeight(order, totalWeight)); //ctx.Update(order, CalculateAmount));// 
        }

        private static void ApplyWeight(Shop.Models.Order order, double Weight)
        {
            order.Totals.TotalWeight = Weight;
        }
    }

When i remove the .match<OrderLine> part. I receive the entire collection.
When i replace it with 

                    .Query(() => orderlines, ol => ol
                    .Match<OrderLine>(o =>true)
                    .Collect())

I receive nothing again.

Any thoughts what the issue might be? Since i checked the code with a UnitTest in this project ( named "LargeTotalRule") and there .Match is used. There it also works.
When it's empty, it's always the type: NRules.Aggregators.FactCollection<Shop.Models.OrderLine>

I'm using nuget version 0.9

**Comment by snikolayev** [comment]
Would you be able to create a unit test that reproduces the issue?

**Comment by NicoJuicy** [comment]
Funny enough, this is my unit test. So I will create a separate package. Yes :)

**Comment by NicoJuicy** [comment]
How do you want the unit test? I currently extracted mine in another project and  uploaded a zip file to 
https://drive.google.com/file/d/1AJrWTKE7d6P4YOyOV6K1yAzqdqDxlKN6/view?usp=sharing

I'm not knowledgeable about NRules internals currently to see which Aggregator/flow is similar to what i've done.

**Comment by snikolayev** [comment]
You are inserting `OrderLine` facts into the session incorrectly. You are inserting a single object of type `IEnumerable<OrderLine>`:
```c#
session.Insert(orderLines);
```
But you need to be inserting individual `OrderLine` facts:
```c#
session.InsertAll(orderLines);
```

**Comment by NicoJuicy** [comment]
You are correct. Thank you
