### ISSUE TITLE
Match operation not stop while matched a fact.

### ISSUE THREAD

**Issue by fooevr** [NRules/NRules#201]
a simple nrules rule:
```C#
Flight flight = null;
Flight preFlight = null;
When()
   .Match(() => flight)
   .Match(() => preFlight, f => f.nextId == flight.fid);
```
insert N facts then fire. every flight fact nextId getter invoke N times, means every preFlight match was match all flight facts even if get the right fact.

a drools rule:
```drools
when
    $flight:FlightEntity()
    $preFlight:FlightEntity(nextId == $flight.fid)
```
insert 7 facts then fire, evert flight fact nextId getter invoke 2 times.
can you tell me why? thank you.

**Comment by snikolayev** [comment]
Currently, a beta condition (that is, a condition that uses more than one fact as input, like here where you have a condition on preFlight and flight) will evaluate on every combination of facts. It could also be done as a hash join on key equality, but NRules does not yet implement it that way. I'm working on it.
Likely Drools already implements such equality joins as hash joins.

**Comment by fooevr** [comment]
thanks
