### ISSUE TITLE
Getting Started Console App

### ISSUE THREAD

**Issue by m2web** [NRules/NRules#204]
I have created a Console App based on the Getting Started page at `https://github.com/NRules/NRules/wiki/Getting-Started`

I am not seeing the Customer object's NotifyAboutDiscount string output "Customer {0} was notified about a discount." What am I doing wrong?

Let me know what you need from me. Thanks.

**Comment by snikolayev** [comment]
Please ask questions on the forum or gitter chat. Use issues to report bugs or request features. 
For this thing it would be helpful to get a reproduction test or code from you.
