### ISSUE TITLE
RuleML or Standardizing Dynamic Rules?

### ISSUE THREAD

**Issue by martinkoslof** [NRules/NRules#209]
I am about to take on a new project where dynamic business rules are required. I have stumbled onto NRules and it looks like a great library. The current system is outdated, uses custom parsing of plain text to generate c# "validation" rules and it simply doesn't scale well and we want to streamline and modularize the application to be micro service based, step functions and server less. Putting the rest of the potential design aside, I was curious if anyone has come up with a standardized way to load dynamic rules into the RuleBuilder. I don't know much about RuleML, but that seems to be a standard with some cross community support.

Has anyone successfully loaded a RulesRepository using JSON, RuleML or some standard format? One thing that makes our situation a little less "dynamic" is rules are done prior to the client application being live, and it is also acceptable to recompile or reload the application when business validation rules change. I envision storing a bunch of rules in a database as rows, such as varchar columns and then parsing them in C# into expressions in the load method of a RulesRepository is probably clunky and error prone.

I'd love any insight to how people have done production scenarios where rules can be dynamic, call functions via Do() and how they designed this process.

Thanks in advance.

**Comment by martinkoslof** [comment]
Hmmm, so I just stumbled into this as well:

https://github.com/NRules/NRules.Language

Is this an approach people use for dynamic rules? Looks like any string with the proper syntax can be provided. This also appears to be early in development. Is this full throated and any sort of rule you can build via C# and DSL at compile time is supported?

**Comment by snikolayev** [comment]
Sorry for late response. Architecturally, NRules can support different kinds of DSLs and rule serialization formats. I thought about adding support for JSON as a rules serialization format, but haven't looked at RuleML. So far no one has asked about RuleML, but if there is enough interest we can look into it.
If you are interested in gathering opinions from NRules users, you are probably better off asking the question on the NRules forum or gitter chat.
I personally prefer C# DSL as there is a good existing tooling ecosystem already around it, such as IDE, debugger, etc. It's very hard to get the same level of rule writer experience with any other DSL.
NRules.Language is not yet fully feature complete, so not all rule constructs are supported. You can look at integration tests inside NRules.Language project to see what's supported.
Let me know if you have further questions.
