### ISSUE TITLE
RuleRepeatability.NeverRepeat?

### ISSUE THREAD

**Issue by a046** [NRules/NRules#211]
This is kind of a feature request and kind of a support question, just curious on what you think. I'm especially curious if anyone is aware if this is something that is supported in other RETE implementations.

The RuleRepeatability.NonRepeatable setting will still cause a rule to get re-run if the conditions get re-asserted, does it make sense to have another setting that never repeats even under those circumstances? I'm interested in this behaviour as a way to retain forward chaining but prevent the possibility of recursion via indirection (e.g. two rules changing the dependent properties)

The current mechanisms are well documented here but don't provide an exact solution: https://stackoverflow.com/a/50014106/1433362

I think this use case is easily handled if the fact model is modified to support it, but this does not seem like a "pure" approach to me. For example, I think using an agenda filter with a readonly property would allow the same behaviour and might often be possible without needing to pollute the fact model.

**Comment by a046** [comment]
Seems like I misunderstood the agenda filters anyway, decided to try with a constant expression ("true") and realised I had it backwards -- the activation is removed from the agenda regardless of filters, but filters can let a rule not fire without the activation being removed.

So if I wanted to achieve this with agenda filters, i'd lose the benfits of Rete it seems.

**Comment by snikolayev** [comment]
The key point here is that all methods for recursion control, such repeatability and agenda fillers are all built around activations. Once the activation is destroyed, all information about it is gone, so when the same facts are reasserted the activation is created again and will fire. Supporting some sort of filtering across activation would mean remembering facts after they are long gone from the session, which is probably not a good idea.
What you can do is implement a custom agenda filter (using IAgendaFilter interface), where you could have some sort of a session wide memory of activation that existed, and rejecting new activation that you have seen the past.
I also don’t think agenda filters negate the benefits of rete. Can you please elaborate why you think that?

**Comment by a046** [comment]
Makes sense, thanks for the suggestion!

The comment about agenda filters negating the benefits of rete was specifically about shifting ALL conditions into agenda filters to retain activations. Doing that would mean the rete network is never constructed, you don't get partial activations etc.

**Comment by snikolayev** [comment]
Thanks for clarifying, that’s an important call out. Indeed, if conditions are shifted to filters, the benefits of rete will be lost. The general idea is that the conditions remain where they are, and filters contain simple gate conditions on top of that to prevent unwanted activations. Good point
