### ISSUE TITLE
Control batch behavior for bulk insert/update/retract methods

### ISSUE THREAD

**Issue by Smurf-IV** [NRules/NRules#214]
You state that the bulk versions of the add and insert are better, but how does one deal with a way of inserting a lot of facts that may contain some that are already inserted ?

Can the API's be extended that do the equivalent of  _bool noFailIfDuplicate=true_
```c#
    /// <summary>Inserts new facts to the rules engine memory.</summary>
    /// <remarks>Bulk session operations are more performant than individual operations on a set of facts.</remarks>
    /// <param name="facts">Facts to insert.</param>
    /// <param name="noFail">Do not throw exception if a fact is already in the Session</param>
    void InsertAll(IEnumerable<object> facts, bool noFail=true); 
```

**Comment by snikolayev** [comment]
Have you looked at the existing `TryInsertAll`? It doesn't insert anything if any of the facts is a duplicate, but it returns a result that indicates which ones are duplicates, so you can exclude them and try inserting the ones w/o duplicates again.
Let me know if that works for you.

**Comment by Smurf-IV** [comment]
Thanks for the response.
Yes I saw that, I did not realise it was a list that was created of failed items, or I did and then it occurred to me the following so dismissed it, and made the above request.
The code is supposed to be performant ?
So 
- Create big a _list_ of items
- Call TryinsertAll, which goes through the _list_, and compares with the _internal_ facts
- Fail, Create _another_ list of failed items and return
- Calling code goes through the failed _list_ and removes from the big _list_
- Attempt TryInsertAll, Again and got through the slightly smaller _list_ and check the _internal_ facts
- Nothing is duplicate, so insert the _list_

This does not sound like a performant solution that is any better than calling TryInsert on each individual item _once_ !

**Comment by snikolayev** [comment]
I agree it makes sense to have ability to control the behavior of bulk operations. Adding an optional parameter to TryXxxAll methods, where you can specify the AllOrNothing behavior (default) or to SkipFailed.
