### ISSUE TITLE
Fluent Forward Chaining

### ISSUE THREAD

**Issue by rmanjusha** [NRules/NRules#217]
I see a possibility of getting into infinite loops if forward chaining is not handled correctly in code. Does NRule has options to handle infinite loop internally?

**Comment by snikolayev** [comment]
There is no mechanism in NRules that will guarantee that infinite loop cannot occur. But there are techniques on how to structure your rules to avoid it. I recommend to look at this SO question, that covers it: https://stackoverflow.com/questions/49946688/best-way-to-achieve-forward-chaining-in-nrules
