### ISSUE TITLE
Querying collections

### ISSUE THREAD

**Issue by rmanjusha** [NRules/NRules#219]
Hi,

Could you please share details on how to query collection in a fact? Below is my fact. I am inserting CommodityItems object in session memory .  I need  to query Items to check if Item of particular ItemCode has quantity greater  than 50. Below is the rule query. But isn`t  working.

**Rule**

            return When()
                .Match<CommodityItems>(() => commodities)
                .Query(() => items, x => x
                    .Match<Commodity>(
                        o => o.ItemCode == "Product1")
                    .Collect())
                .Let(() => total, () => items.Sum(x => x.ItemQuantity))
                .Having(() => total > 0);

**Fact**
 public class CommodityItems 
    {
           public IList<Commodity> Items { get; set; }
    }

**Comment by snikolayev** [comment]
It's unclear from the rule you provided what you are trying to do. For example, what's the relation between Commodity and CommodityItems? What are you inserting into the NRules session?

**Comment by snikolayev** [comment]
I missed that you said you are inserting the CommodityItems object into the session. Assuming the Items collection is a `List<Commodity>`, I think the following rule will give you what you are looking for.
```c#
    public class TestRule : Rule
    {
        public override void Define()
        {
            CommodityItems commodities = null;
            IEnumerable<Commodity> items = null;
            int total = 0;

            When()
                .Match(() => commodities)
                .Query(() => items, q => q
                    .From(() => commodities)
                    .SelectMany(x => x.Items)
                    .Where(x => x.ItemCode == "Product1")
                    .Collect())
                .Let(() => total, () => items.Sum(x => x.ItemQuantity))
                .Having(() => total > 0);

            Then()
                .Do(x => Console.WriteLine($"Total Quantity for Product1: {total}"));
        }
    }
```

**Comment by snikolayev** [comment]
The reason you cannot match `Commodity` facts directly within the query is because you are not inserting them into the session (you are only inserting the `CommodityItems` fact)

**Comment by rmanjusha** [comment]
Perfect! Thanks @snikolayev
