### ISSUE TITLE
Add support for CancellationToken in Fire method

### ISSUE THREAD

**Issue by a046** [NRules/NRules#221]
What are your thoughts on adding a [CancellationToken](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=netframework-4.8) argument in Session.Fire()? This would be to allow the execution to halt if it's taking too long (likely infinitely looping due to chaining).

It seems a check to actionContext.IsHalted is already checked in each iteration, so i'm sure the two could somehow be merged if efficiency is a problem.

I think long running actions could be handled by exposing the cancellation token on IContext which would only leave potential gaps if the matching process/RETE maintenance is slow and not cancellable.

**Comment by snikolayev** [comment]
@a046 I think this is a reasonable improvement.
For Fire method itself, you could just call Fire(1) in a loop and bail out if you get too many cycles. But it does not help with long-running actions, so I think your proposal makes sense.

**Comment by a046** [comment]
Just another thought, a comprehensive solution might also support/check the CancellationToken in RuleCompiler.Compile as that could be a slow/costly part. 

Maybe also InsertAll for the initial seeding of the engine with facts? Unless you'd recommend calling Insert in a loop externally.
