### ISSUE TITLE
Compare DateTime

### ISSUE THREAD

**Issue by PatryxCShark** [NRules/NRules#222]
Hi,
As I noticed there is a functionality to have condition for DateTime but how to create condition only for time?
How can I deal with condition based only on current time? For example I want to check if current hour with minutes is between two different values (hour and minutes) or greater/less than hour with minutes.
Example: now is 02:01 am. I want to check if now is greater or equal 01:59am
Thank you in advance for helping.

**Comment by snikolayev** [comment]
NRules computes matches using the conditions specified in the rules and stores those matches and partial matches inside it's Rete network. This means conditions won't get re-evaluated again unless some of the input facts change. To compare anything with the current time, you would need to create a time fact, and periodically update it inside the session, with the frequency that suites your needs.
Then the conditions would just compare time using the methods exposed by DateTime.
