### ISSUE TITLE
ClaimsAdjudication Sample?

### ISSUE THREAD

**Issue by btompkins** [NRules/NRules#226]
I'm not able to build the sample.  Also, it looks like there's some broken code? For example : 

samples/ClaimsAdjudication/ClaimsExpert.Rules/StatusRules/ApproveClaimRule.cs

```
 When()
                .Claim(() => claim, c => c.Open)
                .Not<ClaimAlert>(ce => ce.Claim == claim, ce => ce.Severity > 1);
```

Should be 

 ```
When()
                .Match<Claim>(() => claim, c => c.Open)
                .Not<ClaimAlert>(ce => ce.Claim == claim, ce => ce.Severity > 1);
```

Hope I'm not misunderstanding

**Comment by snikolayev** [comment]
What’s the break that you are observing?

**Comment by btompkins** [comment]
I'm sorry, does the above compile?

**Comment by btompkins** [comment]
I got it. Sorry!
