### ISSUE TITLE
Writing DSL for dynamic expressions

### ISSUE THREAD

**Issue by baltuonis** [NRules/NRules#228]
Hi, 

I'm trying to write a DSL extensions for Exists method, which receives a condition, that includes methods that receive matched parameters.

Example:

```csharp
public static ILeftHandSideExpression ExistsPowerUnit(this ILeftHandSideExpression lhs,
			Expression<Func<IPowerUnit, bool>> condition) =>
			lhs.Exists<IEnumerable<IVehicle>>(vehicles => vehicles.OfType<IPowerUnit>()
				.Any(condition.Compile()));
```

However this fails, because I'm compiling too soon & matched parameters that are within the condition are being passed as null.

Is there a way add that expression uncompiled to make that work?

**Comment by snikolayev** [comment]
You need to compose expressions - do NOT compile the expression into the delegate, as that defeats the whole purpose.
Look at this example: https://stackoverflow.com/questions/53158857/nrules-issue-using-dsl-extension-on-rule-with-custom-base-class

**Comment by snikolayev** [comment]
This is how an implementation might look:
```c#
public static class DslExtensions
{
    private static readonly MethodInfo FilterMethod;

    static DslExtensions()
    {
        FilterMethod = typeof(DslExtensions).GetMethod(nameof(PowerUnitWithPredicate),
            BindingFlags.NonPublic | BindingFlags.Static);
    }

    public static ILeftHandSideExpression ExistsPowerUnit(this ILeftHandSideExpression lhs,
        Expression<Func<IPowerUnit, bool>> condition)
    {
        var vehicles = Expression.Parameter(typeof(IEnumerable<IVehicle>), "vehicles");

        var expression = Expression.Lambda<Func<IEnumerable<IVehicle>, bool>>(
            Expression.Call(null, FilterMethod, vehicles, condition),
            vehicles);

        return lhs.Exists(expression);
    }

    private static bool PowerUnitWithPredicate(IEnumerable<IVehicle> vehicles, Func<IPowerUnit, bool> predicate)
    {
        return vehicles.OfType<IPowerUnit>().Any(predicate);
    }
}
```
Though I'm not saying anything about the functional correctness of this extension - it does the same thing your code was meant to do. Do you really insert a collection of IVehicle as a single fact into the session, or do you insert them as individual facts?

**Comment by baltuonis** [comment]
Hi Sergiy,

Thanks for prompt response.
Yes we are putting whole IVehicles collection as a fact, having vehicles as separate facts was less manageable and led to more boilerplate in the rules.

I was trying to come up with a correct expression yesterday but got stuck with the `OfType` part.

Your example seems to work, I've ran a few unit tests and they pass. I'll update other parts & keep testing.
Thank you! Now our rules will look a bit nicer.

Also we appreciate your work on NRules

**Comment by snikolayev** [comment]
Great to hear it works
