### ISSUE TITLE
Lastest version 0.9.0 does not support session events OnConditionFailedEvent and OnActionFailedEvent

### ISSUE THREAD

**Issue by sandeepso** [NRules/NRules#229]
Hi,
I have upgraded NRule library in my project to latest version 0.9.0 and noticed that its not supporting events  OnConditionFailedEvent and OnActionFailedEvent.

 I have used LhsExpressionFailedEvent & RhsExpressionFailedEvent for OnConditionFailedEvent is that correct?

What is equivalent of OnActionFailedEvent I don't find any event for same, please advise.

Thanks!

**Comment by snikolayev** [comment]
LhsExpressionFailedEvent replaces all left-hand side failed events (conditions, binding expressions and aggregate expressions), and RhsExpressionFailedEvent replaces that for actions.
