### ISSUE TITLE
Unable to find assembly 'NRules.Fluent,

### ISSUE THREAD

**Issue by sandeepso** [NRules/NRules#230]
I am using NRule in my solution that target .NET framework 4.8 
After NRule lib upgrade to 0.9.0 its not loading rules, getting below error
Unable to find assembly 'NRules.Fluent, Version=0.9.0.0, Culture=neutral, PublicKeyToken=8ad544355a4a2176'

**Comment by snikolayev** [comment]
Make sure you upgrade NRules to the same version in all projects that use it. Please let me know if this resolves your issue.

**Comment by sandeepso** [comment]
yes it resolve assembly load issue
