### ISSUE TITLE
Prevent infinite loops

### ISSUE THREAD

**Issue by sdg002** [NRules/NRules#234]
Hi All,
Consider a scenario where I have a faulty rule implementation which always returns a True value in the Match clause, thereby causing the rule engine to run infinitely.
Is there any property that would help me specify a limit on the number of times the rule engine executes - if it exceeds this number then throw a well defined exception.

Thank you,
Sau

**Comment by a046** [comment]
There's a few mechanisms in NRules to prevent infinite recursion, there's some discussion both in this issue and in the articles linked: https://github.com/NRules/NRules/issues/211

**Comment by snikolayev** [comment]
@sdg002 also consider using [Session.Fire(1)](http://nrules.net/api/html/M_NRules_ISession_Fire_1.htm) in a loop. In this case you will get control after every rule execution, and will be able to decide whether to continue firing rules or to terminate execution.
