### ISSUE TITLE
How to use DbContext in a rule engine nrules

### ISSUE THREAD

**Issue by wangadeketan** [NRules/NRules#235]
Hi, i am new at rule engine i am trying to add a dbcontext in a rule. Do you have any ideas about this.
```
public class ImportEmployeeExcel : Rule
    {

        public override void Define()
        {
            IRepository<Employee, long> employeeRepository = null;
            Employee employee = null;

            Dependency()
                .Resolve(() => employeeRepository);

            When()
                .Match<Employee>(() => employee, e => e.TenantId != null);

            Then()
                .Do(_ => employeeRepository.InsertAsync(employee));

        }
    }
```
Rule load 
```
//Load rules
            var employeeRepository = new RuleRepository();
            employeeRepository.Load(x => x.From(typeof(ImportEmployeeExcel).Assembly));
            //Compile rules
            var factory = employeeRepository.Compile();

            //Create a working session
            var session = factory.CreateSession();
            session.Insert(employeeProfile);
            session.Fire();
        }

```

**Comment by snikolayev** [comment]
@wangadeketan you can inject a dependency into the rule, either a DbContext directly, or indirectly via some repository, like you indicated in your example.
You can inject a dependency either directly into the rule class during it's instantiation (see https://github.com/NRules/NRules/wiki/Fluent-Rules-Loading#rule-activation) or resolve dependencies dynamically, like you indicated in your example (see https://github.com/NRules/NRules/wiki/Rule-Dependencies).

Judging by your example, it seems you tried the second option. Did it not work? If so, what didn't work?

**Comment by wangadeketan** [comment]
@snikolayev Thanks for replay.
Did it not work? If so, what didn't work? >> Actually when i start my application it's throw me error like please define a dependencies resolver for resolving dependency .
I have gone through this links [https://github.com/NRules/NRules/wiki/Rule-Dependencies]

In order to be able to use rule dependencies, one must implement IDependencyResolver interface and set resolver instance either at the ISession or at the ISessionFactory level.

I can not  understand how to  define a IDependencyResolver interface and resolver instance at the ISession

**Comment by snikolayev** [comment]
Create a class that implements IDependencyResolver interface and delegate the dependency resolution to your DI container.
What DI container are you using?
For an example of IDependencyResolver implementation with Autofac see [AutofacDependencyResolver](https://github.com/NRules/NRules/blob/develop/src/NRules.Integration/NRules.Integration.Autofac/NRules.Integration.Autofac/AutofacDependencyResolver.cs).
