### ISSUE TITLE
Setting default rules

### ISSUE THREAD

**Issue by nmarun** [NRules/NRules#237]
Hi,

I'm trying to build a rules engine and was looking at your page: https://github.com/NRules/NRules/wiki/Rule-Builder.

I want to know if this is do-able:

![image](https://user-images.githubusercontent.com/5554175/92388136-672fca00-f134-11ea-9de9-fb8d1795c679.png)

When the request is JP, the first rule should be selected; for any other country, it should pick up the second one. I don't want to put an entry for all the countries we'll be dealing with, hence the '*'.

Is this supported?

Also, is there a UI that can be used by clients to populate the rules by a business user?

Thank,
Arun

**Comment by a046** [comment]
To do a rule like this in NRules, you'd have to re-model it into the appropriate format in some way, most likely by using a higher priority for more derived rules (e.g. country = JP first) and not running later rules if the status is set.

There's no UI provided for NRules, you can either use the Fluent API with visual studio or build your own on top of the rule builder API.

If your rules are all of this form, you might be better off with a decision table as it's simple to write a UI for and works well for this type of rule. One problem you might run into with that approach is prioritizing ambiguous matches if you have more than one field that allow wild cards.

By the way, I think it's recommended to ask questions like these on the gitter chat or StackOverflow. GitHub issues for NRules are mostly for bug reports and requests.

**Comment by snikolayev** [comment]
@a046 thank you for answering this question, I have nothing to add. @nmarun if you have follow up questions on this, please ask on the forum, SO or gitter, as @a046 mentioned.
