### ISSUE TITLE
NRules Autofac integration package does not support Autofac 5.2.0

### ISSUE THREAD

**Issue by wangadeketan** [NRules/NRules#238]
I am getting exception with the following code
`
var builder = new ContainerBuilder();
var types = builder.RegisterRules(x => x.AssemblyOf(typeof(DslExtensions)));
builder.RegisterRepository(r => r.Load(x => x.From(types)));
builder.RegisterSessionFactory()
                .OnActivating(e => new RulesEngineLogger(e.Instance))
                .AutoActivate();
`
System.MissingMethodException: Method not found: 'Autofac.Builder.IRegistrationBuilder`3<!0,!1,!2> Autofac.Builder.IRegistrationBuilder`3.PropertiesAutowired(Autofac.PropertyWiringOptions)'.
   at NRules.Integration.Autofac.RegistrationExtensions.RegisterSessionFactory(ContainerBuilder builder, Func`2 compileFunc)
   at NRules.Integration.Autofac.RegistrationExtensions.RegisterSessionFactory(ContainerBuilder builder)

Packages:
Autofac = 5.2.0
NRules.Integration.Autofac = 0.9.0

**Comment by snikolayev** [comment]
The latest build was integrated against Autofac 3.3.1. There were breaking changes in Autofac since then, that's why it breaks at run time. You can recompile NRules.Autofac.Integration against Autofac 5.2.0 from sources yourself as a workaround.
For the next NRules release I'll integrate against the latest Autofac.

**Comment by snikolayev** [comment]
Targeting netstandard 2.0 now in the integration package.
Upgraded to Autofac 4.0.0+ (tested with 4, 5 and 6).
Simplified rules and repository registration. The minimal registration example becomes:
```c#
var builder = new ContainerBuilder();
builder.RegisterRuleRepository(x => x.AssemblyOf<Program>());
builder.RegisterSessionFactory();
```
