### ISSUE TITLE
Port wiki documentation into the repo to foster collaboration

### ISSUE THREAD

**Issue by ralphromero** [NRules/NRules#240]
Wiki Getting Started page order class is missing IsOpen property which is in the SimpleRules sample in the repo.
Also think about adding the wiki pages to the repo.

**Comment by snikolayev** [comment]
Getting started page was never meant to be compatible with any of the samples. It's a minimal code project to paste into your solution and get NRules working quickly. Samples are meant to be more broad and feature-rich. So, I don't think that page needs updating.
I'm interpreting the second part of your statement as - wouldn't it be nice if documentation was stored in a way that others can contribute. Good point, as built-in wiki on GitHub does not lend itself well to that form of collaboration. I'm thinking about porting documentation into restructured text or similar format, and putting it into a separate repo. I'm going to repurpose this issue for that.

**Comment by snikolayev** [comment]
Need to survey available formats for storing documentation artifacts and compiling them into a working documentation website (e.g. restructured text), choose one, port documentation to that form and put into a separate repo under NRules org.

**Comment by douglasg14b** [comment]
Could work as a collection of markdown files in this repo? That alone lets you collab on it, since you can achieve similar functionality as the wiki (sans the sidebar)

You can then render those out with any number of static doc-site generators from that markdown, without detracting from the in-repo readability or discoverability?

**Comment by snikolayev** [comment]
@douglasg14b yes, that's the general idea here. It's the second part - generating a doc site from the markdown as part of the build process - where I'm looking for help from the community. I looked at sphinx and mkdocs, both seem capable. Any experience with these or other doc generators?

**Comment by douglasg14b** [comment]
@snikolayev Not really, but I can *probably* make a PR in the near future that uses one of the major doc engines 🤔 

There is something you need to do on your end though, which is to enable github pages. I can fork this repo and play around there and see what the ideal settings might be so there is less fiddling here, and report back.

Edit: Just noticed your `main` branch is pretty old, any plans on updating it to `develop`?

**Comment by snikolayev** [comment]
@douglasg14b there is already a separate github pages-enabled repo in NRules: https://github.com/NRules/NRules.github.io 
I think the way this should work is that the documentation markup goes to this current repo, then, as part of the build process, that markup is converted to static html docs, which are published to the github pages-enabled repo. So, the key part here is to find a tool that does that conversion.
One way this can be done, indeed, is by using a markdown processor right there in the github pages (https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll). But I personally would rather use an external documentation build processor, to not depend on the github pages capability and be able to host the documentation anywhere.

Regarding the main branch - planning a release later this year, which will merge develop to main.

**Comment by douglasg14b** [comment]
That's an odd setup 🤔  One of Github page's advantage is that you can have pages for your *existing* repo. Which helps with the problem of: The further docs are from the code (As in, not in the repo), the less likely they are to be updated & collaborated on. This is also rather conventional on GitHub, and conventional choices help devs collab, but that's just my stance on it anyways.

The separate repo-want makes this harder than it is unfortunately :/ 

As for use-anywhere'ness. Using MkDocs or VuePress in a github action (please not `Jekyll`, 3rd party tools are really overcomplicating something this mundane 😅 ) is going to run the *same basic commands* you would run to publish it anywhere else (locally included), with the same tools. And your docs build output will be pushed in a `gh-pages` (or other) branch for example. So it's entirely portable, it's just static site output which can be tossed up anywhere.

<hr>

EDIT:

^ Note: Your project not mine, so I'm just offering up my opinion in my area of expertise.

**Comment by snikolayev** [comment]
DocFX (https://dotnet.github.io/docfx/) can generate API documentation from xml-doc comments, and thus replace Sandcastle, which is quite outdated now. It can also generate a documentation site, combining conceptual documentation in markdown format and the API documentation. So, the path forward here is to port both, wiki and API docs to DocFX.
The generated static content for the site will still be uploaded to https://github.com/NRules/NRules.github.io
