### ISSUE TITLE
Unable to ensure facts retracted if GetHashCode is overriden

### ISSUE THREAD

**Issue by Patrico12345** [NRules/NRules#244]
We have a scenario where we need to ensure our Session persists across multiple test runs. Because of this we often clear all facts out of the Session between each new use of the Session. 
This caused us to run into an interesting scenario where we have modified an object after it has been inserted into the Session. However, when attempting to retrieve the object from the Session, we're able to successfully query the object, but when we attempt the Retract, it fails because the hashcode is being re-generated when the fact is pulled from the private `_workingMemory`'s `_factMap `dictionary.

I've thrown together some quick code to illustrate this issue, the following test will fail because the fact cannot be found:
```
[Fact]
public void DummyTest1()
{
    var fact3 = new FactType3 { TestProperty = 42 };
    Session.Insert(fact3);
    fact3.TestProperty += 1;
    var facts = Session.Query<object>();
    Session.RetractAll(facts);
}

public class FactType3
{
    public int TestProperty { get; set; }

    public override bool Equals(object obj)
    {
        return base.Equals(obj);
    }

    public override int GetHashCode()
    {
        var hashcode = base.GetHashCode();
        hashcode += TestProperty.GetHashCode();
        return hashcode;
    }
}
```

Does it make sense to do a "force retraction" and exposing something like the following being added to WorkingMemory?
```
public void RemoveAllFacts()
{
    _factMap.Clear();
}
```

**Comment by snikolayev** [comment]
There are a couple of things. First, what’s the point of keeping the session around if you retracted all the facts from it? Keep the session factory, but throw out the session after each test and create a fresh session every time. For this reason it doesn’t quite make sense to me to create a Clear method on the session as that’s equivalent to just creating a brand new session.
Second, I’m not going to lecture on the good engineering practices, but using a mutable field in a GetHashCode is a disaster waiting to happen. IMO the code behaves as expected.
