### ISSUE TITLE
I want to use this library to implement cellular automata

### ISSUE THREAD

**Issue by wzxinchen** [NRules/NRules#245]
There are some doubts about performance. My automaton is developed for games and is used to simulate natural environments in games.
I will add a lot of entities, such as people, animals, buildings, etc., each entity has its own rules to simulate the natural environment.
The specific scenario is, if I have an entity of one million people (equivalent to an instance of the person entity), then I want to perform a series of operations on the person whose attribute A is 1, and perform some other operations on the person whose attribute A is 2. operating.
I have two implementation schemes:
1. Directly query all people in the Rule (ie When().Match(()=>humans)), and then after finding out, I will judge the value of attribute A in Then to perform related operations. The problem with this solution is that it has nothing to do with NRules, which is equivalent to writing a loop myself.

2. Implement two rules, one for the person whose attribute A is 1, and the other for the person whose attribute A is 2, perform different operations. The advantage of this scheme is that it makes full use of the functions of NRules, but one possible disadvantage is whether the engine will perform a foreach traversal for these two rules to find eligible persons. If this is the case, once I With more conditions, this performance overhead is terrifying.

My question has been mentioned in the second plan, thanks for the answer!

**Comment by snikolayev** [comment]
@wzxinchen NRules is based on the rete algorithm (it's a so-called production rules engine), as such it does not rescan the input facts, but calculates the conditions once and stores the partial matches. So, the engine is not going to traverse the facts in either case you are describing. You can get more details about how production rules engines and rete here: https://en.wikipedia.org/wiki/Rete_algorithm
But there are other considerations that you should look into to determine whether NRules is suitable for your use case. The biggest one is that rete sacrifices memory for performance, and so you should test a realistic scenario and see if the memory footprint is acceptable. This may be particularly tough for games, as extra memory allocations may cause more frequent/longer GC runs.
Finally, please ask further questions on the gitter channel or on the google groups forum. I'm trying to reserve issues on GitHub for bug reports and feature requests.
