### ISSUE TITLE
Private Types ignored when using RegisterRuleRepository

### ISSUE THREAD

**Issue by marmy28** [NRules/NRules#248]
I tried using

`builder.RegisterRuleRepository(i => i.Assembly(this.ThisAssembly).PrivateTypes());`

but the private types were ignored. I believe the issue could be with
[RegisterRuleRepository](https://github.com/NRules/NRules/blob/57bd489bf5559e86baa07e524f01fb4e21b4d24f/src/NRules.Integration/NRules.Integration.Autofac/NRules.Integration.Autofac/RegistrationExtensions.cs#L39)
not taking into account the `scanAction` that was provided to the function when loading the types. (At least when debugging that was the place the types started being ignored.)

**Comment by snikolayev** [comment]
This bug and the fix apply to NRules.Integration.Autofac
