### ISSUE TITLE
Q: Autofac DI best practices

### ISSUE THREAD

**Issue by kirk-marple** [NRules/NRules#256]
Just getting started with NRules, and I've gotten it working, but want to make sure I'm doing it correctly.

For setting up DI, I'm using:
```
            builder.RegisterRuleRepository(x => x.Assembly(typeof(RuleHelpers).Assembly));
            builder.RegisterSessionFactory();
```

And to use a rule repository, I'm using:
```
(1)            var repository = new RuleRepository {Activator = new AutofacRuleActivator(KnowledgeFixture.Container) };

(2)            repository.Load(x => x.From(typeof(RuleHelpers).Assembly));

            var factory = repository.Compile();
            var session = factory.CreateSession(session => session.DependencyResolver = new AutofacDependencyResolver(KnowledgeFixture.Container));

[...]
            session.Fire();
```

Currently, running this in an XUnit test fixture to understand it  better.

Should I need to create a rule repository each time, or should I be able to use DI and just ask for the default rule repository (and skip the lines I marked as (1) and (2)?

I tried adding IRuleRepository and RuleRepository as DI parameters in my test class, but it couldn't find either.

Thanks!

**Comment by kirk-marple** [comment]
Closing; this is an XUnit DI issue.

**Comment by snikolayev** [comment]
XUnit aside, in general, you should only need to create the rule repository and session factory once. At that point the session factory is the representation of the compiled rules, that can be reused throughout the lifetime of the application to create rule sessions.

**Comment by kirk-marple** [comment]
Much appreciated, thanks @snikolayev   I have it working well now with Autofac, outside of our tests.

**Comment by Sunyao-work** [comment]
@kirk-marple I want use NRules.Integration.Autofac, but I can't find any demo for this. so can you help me?
