### ISSUE TITLE
NRules with Asp.Net Core scoped dependency could not be resolved

### ISSUE THREAD

**Issue by AvtsVivek** [NRules/NRules#265]
Posted the same on [SO](https://stackoverflow.com/q/67892131/1977871) as well

I am getting the following error when I run the sample [here](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/NRulesWithAspNetCore).

    Cannot resolve scoped service 'IPersonService' from root provider.

I want to inject the service [IPersonService](https://github.com/AvtsVivek/ElsaBugReports/blob/main/src/NRulesWithAspNetCore/NRulesWithAspNetCore/Services/PersonService.cs#L10) into the rule [MalePersonRule](https://github.com/AvtsVivek/ElsaBugReports/blob/main/src/NRulesWithAspNetCore/NRulesWithAspNetCore/Rules/MalePersonRule.cs)

Note that this same service [IPersonService](https://github.com/AvtsVivek/ElsaBugReports/blob/main/src/NRulesWithAspNetCore/NRulesWithAspNetCore/Services/PersonService.cs#L10) is injected into the [HomeController](https://github.com/AvtsVivek/ElsaBugReports/blob/main/src/NRulesWithAspNetCore/NRulesWithAspNetCore/Controllers/HomeController.cs#L18).  

I have registered this IPersonService as scoped service in the [Startup.cs](https://github.com/AvtsVivek/ElsaBugReports/blob/7c8ceec99d14a7190943137f9186b735c0457bbf/src/NRulesWithAspNetCore/NRulesWithAspNetCore/Startup.cs#L30) class.

I used this [NRules.Integration.AspNetCore nuget package](https://www.nuget.org/packages/NRules.Integration.AspNetCore/) and got the error.  So to understand more I included the source of that [nuget from this git hub repo](https://github.com/cloudb0x/NRules.Integration.AspNetCore) into my [solution in this folder](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/NRulesWithAspNetCore/NRulesWithAspNetCore/NRulesNugetSource).

How do I register a service in request scope so that that service will be injected into the Rule as well with the same scope? Is this possible?

I understood that the Rule cannot be at Request scope. The Rule is instantiated at the start of the application and then the same is used for the rest of the life time for all the requests. I want the service dependencies to be at request scope, meaning that service to be instantiated afresh for each new request. Is this possible?

But I guess [the rule session ](https://github.com/AvtsVivek/ElsaBugReports/blob/7c8ceec99d14a7190943137f9186b735c0457bbf/src/NRulesWithAspNetCore/NRulesWithAspNetCore/NRulesNugetSource/ServiceExtensions.cs#L68)is created afresh for each request. 

So far I was not able to integrate NRules into AspNetCore project satisfactorily. I studied this [NRules.Demo project ](https://github.com/NRules/NRules.demo/tree/main/src)also to get an idea of how to integrate, but facing similar problems. If there is any aspnet core demo project showing how to integrate please do share. 

What am I missing?

The [working solution ](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/NRulesWithAspNetCore)to reproduce the problem is here for your reference.

**Comment by snikolayev** [comment]
@AvtsVivek sorry for the late response. [NRules.Integration.AspNetCore](https://github.com/cloudb0x/NRules.Integration.AspNetCore) is curated by @cloudb0x, so hopefully they can opine on adding this capability to their library.

The following change to the session registration code, sets up the `IDependencyResolver` with a scoped `IServiceProvider`, and fixes the issue (as the dependency is now resolved via the scoped provider associated with the session.

```c#
private static IServiceCollection RegisterSession(this IServiceCollection services)
{
    return services.AddScoped<ISession>(c =>
    {
        var factory = services.BuildServiceProvider().GetRequiredService<ISessionFactory>();
        var session = factory.CreateSession();
        session.DependencyResolver = new AspNetCoreDependencyResolver(c);
        return session;
    });
}
```

I also posted this answer on SO: https://stackoverflow.com/questions/67892131/nrules-with-asp-net-core-scoped-dependency-could-not-be-resolved
