### ISSUE TITLE
About NRules.Integration.Autofac

### ISSUE THREAD

**Issue by Sunyao-work** [NRules/NRules#266]
I want use  NRules.Integration.Autofac, but can't find any demo for NRules.Integration.Autofac. Can you help me?

**Comment by snikolayev** [comment]
Have you checked this? https://github.com/NRules/NRules/wiki/Rule-Dependencies

**Comment by Sunyao-work** [comment]
This wiki have checked, but it is too simple, I can't understand how to use

**Comment by snikolayev** [comment]
If you have a more complex scenario, can you please describe what it is? And if you tried using the NRules.Integration.Autofac package using the instructions on the wiki, did you face any issues? Did something not work?
