### ISSUE TITLE
In MissManners sample, Guest N4 is both male and female

### ISSUE THREAD

**Issue by marked23** [NRules/NRules#276]
In the MissManners sample, Guest N4 is both male and female.  

Was that maybe intentional, to illustrate some feature?
Was that Guest supposed to be named N3 instead?

**Comment by snikolayev** [comment]
Yep, looks like a typo - feel free to send a PR to fix. There is really no right answer here, as the inference would run with either input. You can change that line to N3, or to Female - it will work either way, just produce different results.
And separately - don't read too much into MissManners example. It's popular for rules engines benchmarking, but kind of cryptic, and does not really show well what this project is all about. Look at SimpleRules samples.

**Comment by snikolayev** [comment]
Fixed in 4b6a35ea7dca64f0a894270018b79aa86313632a
