### ISSUE TITLE
OR does not work with nullable field

### ISSUE THREAD

**Issue by tej-rana** [NRules/NRules#297]
In my code below, the Player.MemberDetails.Joined property is a nullable DateTime.

```
Player player = null;
            Player player = null;
           Player player2 = null;
            var hasPlayerJoined = false;
            When()
                .Match<Player>(() => player, p => p.MemberDetails != null)
                .Let(() => hasPlayerJoined, () => player.MemberDetails.Joined != null)
                .Having(() => hasPlayerJoined)
                .Or(x => x
                 .Match<Player>(() => player2, t => t.Spend == 0));

            Then()
                .Do(ctx => AwardMember());
```
It does not work without Let variable declaration and Having.

It works if I use another property of MemberDetails that is of type int.

Also can you do an OR with two rules leaving them as separate rules?

**Comment by snikolayev** [comment]
@tej-rana can you please post the rule that you are saying does not work? Also, can you please elaborate what do you mean by "does not work"? Does it not fire, or do you see any exceptions?
It would be best if you posted a unit test that exactly showed the problem (e.g. I can only guess the definitions of Player types, but if you provided the minimalistic versions of those in a context of a repro scenario that would be very helpful).

Regarding your second question - yes, you can write OR as two separate rules (which is in fact what the engine is doing behind the scenes).

I also think you got the syntax of the Or clause incorrect. The items being OR'ed must be inside the Or method. E.g.:
```c#
When()
    .Or(x => x
        .And(xx => xx
            .Match<Player>(() => player, p => p.MemberDetails != null)
            .Let(() => hasPlayerJoined, () => player.MemberDetails.Joined != null)
            .Having(() => hasPlayerJoined))
        .Match<Player>(() => player2, t => t.Spend == 0));
```
The above code matches `player` (defined by three clauses) or `player2` or both.

**Comment by snikolayev** [comment]
Closing since there was no further engagement
