### ISSUE TITLE
NRules performance question

### ISSUE THREAD

**Issue by svaza** [NRules/NRules#301]
Hi, 

From the docs it appears that NRules uses Rete algorithm for finding best matching set of rules for given data facts, which improves efficiency.

I believe the algorithm would still iterate over all rules to find the matching rule by processing When().Match(e=> {}) for a given fact data.

So in case if i have few small rules (2-5 rules) which can be managed using plain if/else statements, i won't see any performance gain by using Nrules here, other than making my rule set more simple and manageable. Is this understanding right ?

**Comment by woolfel** [comment]
that's not how RETE works. RETE algorithm compiles a set of rules into an optimized query plan. The query plan is then used to match against the data you give it. If all of the conditions of a rule match, the engine executes the action of the rule. It doesn't "select or iterate" over the rules, that's what a sequential rule engine does to evaluate rules.
