### ISSUE TITLE
DslExtensions Example Error

### ISSUE THREAD

**Issue by gwolbr** [NRules/NRules#305]
I pasted the DslExtensions class into a project and receive this error on the Warning method:

public static IRightHandSideExpression Warning(this IRightHandSideExpression rhs, Claim claim, string message)
    {
        return rhs.Do(ctx => ctx.Warning(claim, message));
    }

(parameter) NRules.RuleModel.IContext ctx
'IContext' does not contain a definition for 'Warning' and the best extension method overload 'DslExtensions.Warning(IRightHandSideExpression, Claim, string)' requires a receiver of type 'IRightHandSideExpression' [EngToErp]csharp(CS1929)

**Comment by snikolayev** [comment]
This seems like a recursive definition, since `Warning` extension method attempts to call the `Warning` extension method.
For the full example that uses DSL extensions see: https://github.com/NRules/NRules.demo/blob/main/src/ClaimsExpert.Rules/ContextExtensions.cs
