### ISSUE TITLE
Documentation Enhancement Request for Advanced - RuleBuilder GroupBuilder

### ISSUE THREAD

**Issue by jamesbascle** [NRules/NRules#350]
In [the article here](https://github.com/NRules/NRules/blob/main/docs/articles/advanced/rule-builder.md/#L1), at the bottom, we see example of how to dynamically build a rule by adding some patterns and expressions.  

Are there any examples of how one might encode a slightly more complex boolean logic tree using the And/Or Groups?

**Comment by snikolayev** [comment]
@jamesbascle take a look at the sample:
https://github.com/NRules/NRules/blob/main/samples/RuleBuilder/CustomRuleRepository.cs

**Comment by jamesbascle** [comment]
Thank you Sergiy.  That makes sense.  However, I notice that if I change the first group in `BuildImportantCustomerRule` to an `And`, and the second to an `Or`, I get a Duplicate Declaration error.  This is identical to the problem I am facing in trying to build my own demo.  Is there a bug in the duplicate declaration detection logic, or is there something fundamentally incorrect about having an `Or` nested inside of an `And`?

**Comment by snikolayev** [comment]
The way that rule is written in the sample, it basically matches `(customer OR (customer AND exists order))`.
If you change the groups like you are saying, it will become `(customer AND (customer OR exists order))` - of course there is a duplicate declaration.
Can you please logically describe what grouping are you trying to create?

**Comment by jamesbascle** [comment]
I'm basically trying to encode arbitrary boolean logic trees from another stored representation into rules in NRules for efficient processing of rules, instead of having to run every rule in some rule corpus.

I may not quite grok what is a "Declaration", then, in NRules terminology.  When I am examining the builder states in both the example and the modified example I mentioned (or in the example I post below), it seems there are two `Declaration`s for `customer:Customer`.  One in the `PatternBuilder` at the top level for the first `Group` in its nested builders, and then another in the nested `Group`'s nested builders' `PatternBuilder`.  But only in the latter case is it considered a duplicate

Obviously in the latter example it is always false, because a customer cannot be both an `IsPremium` and `!IsPremium`, but the duplicate declaration persists if I define another property on the `Customer` and use that in the latter clause instead, as below:

```        
        var builder = new RuleBuilder();
        builder.Name("Important Customer Rule");

        var group1 = builder.LeftHandSide().Group(GroupType.And);

        PatternBuilder customerPattern1 = group1.Pattern(typeof(Customer), "customer");
        Expression<Func<Customer, bool>> customerCondition1 = customer => customer.IsPreferred;
        customerPattern1.Condition(customerCondition1);

        var group2 = group1.Group(GroupType.Or);

        PatternBuilder customerPattern2 = group2.Pattern(typeof(Customer), "customer");
        Expression<Func<Customer, bool>> customerCondition2 = customer => !customer.SomeOtherAttribute;
        customerPattern2.Condition(customerCondition2);

        PatternBuilder orderExistsPattern = group2.Exists().Pattern(typeof(Order), "order");
        Expression<Func<Order, bool>> orderCondition = order => order.Amount >= 1000;
        orderExistsPattern.Condition(orderCondition);

        Expression<Action<IContext, Customer>> action =
            (ctx, customer) => Console.WriteLine("Customer {0} is important", customer.Name);
        builder.RightHandSide().Action(action);
        builder.Build();
```

I would read this as `(Customer IsPremium AND ((!Customer SomeOtherAttribute) OR Order Exists >1000)`, and it seems like a reasonable type of rule to have.

**Comment by snikolayev** [comment]
A declaration is just a name assigned to a pattern that matches facts in the rules engine. It essentially defines the "thing" you get passed to your action when the rule fires. A pattern can match a single fact (like in these cases here) or an aggregation of many facts, if you are using a query. The important thing is that each declaration/pattern defines a separate "thing" that the rule matches.
I think the confusion here comes from trying to apply grouping to two things, where they really are the same thing. In the example you provided it should be `((Customer IsPremium && !SomeOtherAttribute) AND Order Exists > 1000)`. 
Essentially, you only group different patterns.
When using OR group as in the original sample, it's actually two different "customers" - one that is preferred, another that has a large order. 
I hope this helps

**Comment by snikolayev** [comment]
Actually, I don't think I understand what does this even mean logically:
`(Customer IsPremium AND ((!Customer SomeOtherAttribute) OR Order Exists >1000)`

**Comment by jamesbascle** [comment]
> Actually, I don't think I understand what does this even mean logically: `(Customer IsPremium AND ((!Customer SomeOtherAttribute) OR Order Exists >1000)`

It would mean that for the rule to fire, the customer should be either Premium, and either they should not be SomeOtherAttribute, or an order by that customer has a value greater than 1000.

**Comment by snikolayev** [comment]
So, I'm guessing that makes sense if it's the same customer, but AND grouping groups different patterns, so it treats them as different, but they are called the same, hence the duplicate declaration. 
So, the structure you are trying to express is not directly supported, but you can lift OR up, by doing something like this:
`((Customer IsPremium && !SomeOtherAttribute) OR (Customer IsPremium AND Order Exists > 1000))`

**Comment by jamesbascle** [comment]
I see.  I think I've had a bit of a misunderstanding of the overall purpose of this algorithm and library and after some more reading I think I understand a bit better and I may be trying to fit a square peg in a round hole 😅

Again, thank you for your responses and patience Sergiy!
