### ISSUE TITLE
No overload for method 'Verify' takes 2 arguments when testing a rule

### ISSUE THREAD

**Issue by mrhighstone** [NRules/NRules#357]
I'm trying to implement rule tests, as documented [here](https://nrules.net/articles/unit-testing-rules.html). 

However, when trying to use the Verify overload as suggested below:
`Verify(x => x.Rule().Fired(Times.Exactly(3), Matched.Fact<Customer>(c => c.IsPreferred)));`

Unfortunately, the compiler says no:
`No overload for method 'Verify' takes 2 arguments`

Am I missing something? Is the documentation outdated or has the source code been updated?

**Comment by mrhighstone** [comment]
Never mind, got the Fired method wrong defined.

**Comment by snikolayev** [comment]
@mrhighstone  I’m closing the issue then
