### ISSUE TITLE
Propagate fact that caused rule to fire into the actions

### ISSUE THREAD

**Issue by knji** [NRules/NRules#45]
When a rule is fired as a result of all conditions being met on a certain fact, that fact should be propagated or made available to the actions defined as part of the rule, to provide complete context.

If I define the rule like this:

 public override void Define()
        {
            AuthRequestEvent theFact = null;

            if (!Conditions.Any())
                throw new InvalidOperationException("Rule has no conditions");

            var when = When();
            ILeftHandSide leftHand = null;
            foreach (var condition in Conditions)
            {
                leftHand = leftHand == null ? when.Match(condition.Alias, condition.Conditions) : 
                           leftHand.Match(condition.Alias, condition.Conditions);
            }

            var then = Then();
            IRightHandSide rightHandSide = null;

            foreach (var action in Actions)
            {
                Expression<Action<Rule, AuthRequestEvent, AuthIdRangePrereq>> action1 = action;

                if (rightHandSide == null)
                {
                    // TODO: fact that triggered is not available on action...
                    rightHandSide = then.Do(ctx => action1.Compile().Invoke(this, theFact, PreReq));
                }
                else
                {
                    rightHandSide = rightHandSide.Do(ctx => action1.Compile().Invoke(this, theFact, PreReq));
                }
            }
        }

the fact does not get propagated to the action definition.  Action definition sees null.  This is an attempt to parameterize the rule and eventually submit a pull request.

**Comment by snikolayev** [comment]
Hi @knji 
I think you are misusing the rules or misunderstanding how NRules engine works. Fluent rules DSL is supposed to be declarative. There should be no imperative code in the rule definition anywhere outside of the condition expressions or action expressions. This is because "Define" method is only called once by the engine to convert the rule into a canonical rule model (which stores conditions and actions as expression trees), so, obviously you should not be throwing exceptions in the rule definition code, looping with imperative code, etc..

When you are declaring a condition using a Match pattern, and you are binding it to a variable like:
```c#
FactType fact = null;
When()
    .Match(() => fact, f => f.SomeProperty);
```
the variable is actually never assigned to. It is just a mechanism to tell the rules engine the name and the type of the fact, so that when you are declaring actions, it can recognize that it is the same fact. Think of this variable as just a token. I could've used just a string value, but that would be not strongly typed and prone for typos.
In your code you are treating the fact variable as a true variable, expecting that somehow the actual value will get assigned to it, which is simply not true. The actual variable value is always null.

Given rule definition is not imperative code, there this no need to break "When" part of it into separate statements and declare "when" or "condition" variables. Use the fluent approach, treat fact variables as just tokens, and only write code withing the condition and action expressions. See [https://github.com/NRules/NRules/wiki/Fluent-Rules-DSL].
I suggest you also look at integration tests to see examples of well formed rules.

As a final note, it looks like you may be attempting to generate the actual rule at runtime, based on the conditions and actions you defined elsewhere in your application. If this is truly the case, then you would use rule builder to define such a rule (and not fluent DSL). See [https://github.com/NRules/NRules/wiki/Rule-Builder]. But in general, I would recommend sticking with the fluent DSL unless there is a very good reason not to.

I'm marking this issue as invalid and closing it, but I'll be glad to continue the discussion, and if there is anything that comes out of it, you can open a new issue or reopen this one.

**Comment by knji** [comment]
@snikolayev thanks for the detailed response and BTW, this is an excellent library you have put together.  Thank you.

You guessed right that conditions and actions will be defined in another part of the application, hence the need to compose these rules at runtime.  I will look at the rule builder as you have suggested.  I also still have to wrap my head around expression trees, as this lack of understanding may be part of my problem.

One thing I am trying to get out of this exercise is to be able to pass parameters or prerequisites to evaluate the condition against.   Look at this FactBasedRule attempt that derives from Rule.  

```csharp
public abstract class FactBasedRule<TFact, TPreRequisite> : Rule
        where TFact : class 
        where TPreRequisite : class
    {
        public TPreRequisite PreReq { get; set; }
        public string Name { get; set; }

        public IList<RuleCondition<TFact>> Conditions { get; set; }
        public IList<Expression<Action<Rule, TFact, TPreRequisite>>> Actions { get; set; } 

        protected FactBasedRule(string name)
        {
            Name = name;
            Conditions = new List<RuleCondition<TFact>>(10);
        }

        public override void Define()
        {
            TFact fact = null;

            if (!Conditions.Any())
                throw new InvalidOperationException("Rule has no conditions");

            var when = When();
            ILeftHandSide leftHand = null;
            foreach (var condition in Conditions)
            {
                leftHand = leftHand == null ? when.Match(condition.Alias, condition.Conditions) :
                           leftHand.Match(condition.Alias, condition.Conditions);
            }

            var then = Then();
            IRightHandSide rightHandSide = null;

            foreach (var action in Actions)
            {
                Expression<Action<Rule, TFact, TPreRequisite>> action1 = action;

                if (rightHandSide == null)
                {
                    // TODO: fact that triggered is not available on action...
                    rightHandSide = then.Do(ctx => action1.Compile().Invoke(this, fact, PreReq));
                }
                else
                {
                    rightHandSide = rightHandSide.Do(ctx => action1.Compile().Invoke(this, fact, PreReq));
                }
            }
        }

        protected void Validate()
        {
            if (PreReq == null)
                throw new InvalidOperationException("This rule cannot be evaluated without a fact.");
                
        }

        public object Evaluate(TFact fact)
        {
            Validate();

            throw new NotImplementedException();
        }

        public override string ToString()
        {
            return (Name ?? GetType().Name) + ":  Prereq is " + PreReq;
        }
    }
```

Then I have another generic rule based on a certain type of fact like this: 

```csharp
 public class OrgAuthEventRule : FactBasedRule<AuthRequestEvent, OrgAuthPrereq>
    {
        public OrgAuthEventRule(string name) : base(name)
        {
        }
    }
```
with the OrgAuthPrereq class looking something like this:

```csharp
  public class OrgAuthPrereq
    {
        public OrgAuthPrereq(string organization)
        {
            Organization = organization;
        }

        public string Organization { get; set; }
        public int LowRange { get; set; }
        public int HighRange { get; set; }

        public override string ToString()
        {
            return string.Format("Organization:{0}, Low ID:{1}, High ID {2}", Organization, LowRange, HighRange);
        }
    }
```

Then within my application,  I can define some sort of policy or rules repository as follows:

```csharp
 public class PolicyRepository /* TODO: put behind interface */
    {
        //TODO: hardcoding for now...
        public IEnumerable<Rule> GetRules()
        {
            var gearHeadsPrereq = new OrgAuthPrereq("GearHeads");
            var anyOrgPrereq = new OrgAuthPrereq("*"){LowRange = 500, HighRange = 600};
            var fileNameForOrgIdsBetween500And600 = "OrgIdBetween500And600Rule.txt";
            var fileNameForOrgNamesWith5 = "OrgNamesContaining5Rule.txt";
            AuthRequestEvent authEvent = null;

            var rules = new Rule[]
            {
                // rule 1: org name must be GearHeadsr rule
                new OrgAuthEventRule("GearHead in org name")
                {
                    PreReq = gearHeadsPrereq,
                    Conditions = new List<RuleCondition<AuthRequestEvent>>
                    {
                        new RuleCondition<AuthRequestEvent>
                        {
                            Alias = () => authEvent, 
                            Conditions = new Expression<Func<AuthRequestEvent, bool>>[]
                            {
                                x => x.Organization == gearHeadsPrereq.Organization
                            }
                        }
                    },
                    Actions = new Expression<Action<Rule, AuthRequestEvent, OrgAuthPrereq>>[]
                    {
                        (r,f, p) => Console.WriteLine(" rule matched on " + authEvent)
                    }
                },


                // rule 2: org id should be greater than 500 and less than 600
                new OrgAuthEventRule("Org ID > 500 and < 600")
                {
                    PreReq = anyOrgPrereq,
                    Conditions = new List<RuleCondition<AuthRequestEvent>>
                    {
                        new RuleCondition<AuthRequestEvent>
                        {
                            Alias = () => authEvent, 
                            Conditions = new Expression<Func<AuthRequestEvent, bool>>[]
                            {
                                x => !string.IsNullOrEmpty(x.Organization),
                                x => x.OrgId > anyOrgPrereq.LowRange,
                                x => x.OrgId < anyOrgPrereq.HighRange
                            },
                        }
                    },
                    Actions = new Expression<Action<Rule, AuthRequestEvent, OrgAuthPrereq>>[]
                    {
                        (r, f, p) => File.AppendAllText(fileNameForOrgIdsBetween500And600, 
                            string.Format("{0}{1}{2}", f == null ? "auth event not in context" : f.ToString(), 
                            Environment.NewLine,
                            "rule:" + r + Environment.NewLine))
                    }
                },


                 // rule 2: org name contains 5
                new OrgAuthEventRule("Org name contains 5")
                {
                    PreReq = anyOrgPrereq,
                    Conditions = new List<RuleCondition<AuthRequestEvent>>
                    {
                        new RuleCondition<AuthRequestEvent>
                        {
                            Alias = () => authEvent, 
                            Conditions = new Expression<Func<AuthRequestEvent, bool>>[]
                            {
                                x => !string.IsNullOrEmpty(x.Organization),
                                x => x.Organization.Contains("5")
                            },
                        }
                    },
                    Actions = new Expression<Action<Rule, AuthRequestEvent, OrgAuthPrereq>>[]
                    {
                        (r, f, p) => File.AppendAllText(fileNameForOrgNamesWith5, 
                            string.Format("{0}{1}{2}", f == null ? "fact that caused this condition is not in available in context" : f.ToString(), 
                            Environment.NewLine,
                            "rule:" + r + Environment.NewLine))
                    }
                }
              
            };

            return rules;
        }
    }
```
I do realize that my approach may be well of the mark but I hope the approach I am trying to prototype, while abiding to the best practices you have already established, makes some sense.

Again, I am evaluating the options but my main requirement is to be able to supply conditions, actions and pre-requisites at runtime, since these conditions and actions will be user configurable.

Thanks again.

**Comment by snikolayev** [comment]
@knji you basically have two options regarding turning your user-defined parameters into concrete rules:
1. If rules are always the same, and the the only thing that is different is a set of constants (i.e. you want to check that the OrgId is in a particular range), but you don't want to hardcode those constants, then you can replace those constants with properties on the rule class, and set those properties when rules are getting instantiated.
2. If the actual rules are different and you need to dynamically create new expressions at runtime, then rule builder is the only option.

I'm not sure I clearly understand exactly what you are trying to do in the sample you provided. If you could boil it down to a plain English description of one rule and indicate which part of that rule you want to parametrize, I should be able to provide a more specific answer.

P.S. Also, in general, it's better to use [discussion group](http://groups.google.com/group/nrules-users) for questions like this.

**Comment by knji** [comment]
Sergiy, I took the discussion over to the discussion group, thanks.

Klaus
