### ISSUE TITLE
Priority attribute not inheritable

### ISSUE THREAD

**Issue by staylr** [NRules/NRules#53]
The IsInherited property of PriorityAttribute is false, which prevents definition of rule base classes with priority. For example, I have sets of product owner and product rules, where product rules should be run before product owner rules - they may insert facts which deactivate the product owner rules. The priority should be defined in the ProductOwnerRule and ProductRule base classes.

Great project - this looks like the right way to do developer oriented rules where the rules are mostly fixed at development time.

**Comment by snikolayev** [comment]
@staylr do you need this fix released asap, or you can wait for the next release at a normal cadence?

**Comment by staylr** [comment]
Thanks for that. No rush, we're still evaluating.
