### ISSUE TITLE
Create a realistic full-stack sample

### ISSUE THREAD

**Issue by snikolayev** [NRules/NRules#56]

**Comment by kotpal** [comment]
I am interested in helping you with this.

**Comment by snikolayev** [comment]
Awesome! The thing that I started that I had in mind was the health claim adjudication service/app that's in the samples folder. However, if there is a particular subject area that you want to tackle for the sample that's fine too.
The idea for the full stack sample to cover client and server and have user interaction. While I started with a thick client, it can be a thin client as well.

**Comment by snikolayev** [comment]
The full stack sample (demo project) moved to https://github.com/NRules/NRules.demo
