### ISSUE TITLE
Priority no longer changeable at runtime

### ISSUE THREAD

**Issue by jcfarsight** [NRules/NRules#61]
Quick question about your design decision implemented in issue# 47 (priority changed from fluent to attribute syntax). You have stated that it was due to attributes enforcing correct semantics, specifically the number of times it can be specified per rule, which is fair enough.

Would it not have been possible to validate the number of times the priority had been set either at rule compilation time or rule object creation?

Basically I've done a simple rule prototype that has fairly flexible rules through the use of Spring Framework dependency injection. The only inflexible part I've found is that we are unable to easily alter the flow of rules in competing situations because the priority must be baked in at binary compile time.

Do you have any suggestions of how I could go about making this more flexible without needing to add state flags to fact objects?

**Comment by snikolayev** [comment]
In general, priority is considered a crude mechanism to control the order of rule execution in inference engines. I think you will agree that dynamically changing it is a bit hacky.
A more appropriate way would be agenda filters and agenda groups, but NRules does not have these features yet. 
I didn't know that someone was taking advantage of setting priorities at run time. So, I'll add back ability to do that (as an override to a compile time priority) at least until the time that those more advanced features are available.

**Comment by jcfarsight** [comment]
Thanks for the quick response. I certainly do agree that priority mangling is hacky. Agendas would be a far more ideal method of dealing with this sort of situation.

I imagine it's theoretically possible to simulate agenda groups by generating multiple rule factories that are in charge of separate rulesets. Extracting the facts post-processing from one session and injecting them into another could have a similar effect, albeit not as elegant.

Compile time priority should definitely suit most uses cases, it would certainly be nice to have that flexibility in the rare event that it doesn't however.
