### ISSUE TITLE
Unexpected behavior?

### ISSUE THREAD

**Issue by jho1965us** [NRules/NRules#67]
I tried the Sample.SimpleRules and noticed it output "Discount applied ..." twice:
> All active accounts of customer John Doe are not delinquent
> Customer John Doe is important
> Customer John Doe does not have active delinquent accounts
> **Discount applied to orders 123456,123457,123458**
> Customer John Doe has active account #12456789
> Customer John Doe has active account #12456790
> Customer John Doe has over 3 open orders
> Customer Sarah Jones is important
> **Discount applied to orders**
> Customer John Doe was notified about a discount

Adding a customer parameter to call to `PreferredCustomerDiscountRule.LogOrders` revield that the second is also concerning orders by `John Doe` is this second empty collection match an expected behavior?

**Comment by snikolayev** [comment]
The semantics of `Collect` changes because of #62. Now collect will also fire with an empty collection if nothing matches, and it requires the use of `Where` condition if you only want it to match a non-empty collection of facts. I just fixed the sample to account for this change:
```c#
.Collect<Order>(() => orders, ...)
.Where(x => x.Any());
```
