### ISSUE TITLE
Allow matching against objects not necessarily in fact memory

### ISSUE THREAD

**Issue by snikolayev** [NRules/NRules#81]
This feature is very handy when stacking processing of rules after a Query/Collect.
It is the From keyword in Drools & Nools. and would is a very helpful complement to your very
powerful Query.  
Drools:http://blog.athico.com/2007/06/chained-from-accumulate-collect.html
Nools: https://github.com/c2fo/nools#from-constraint

Below is a made up, But is there was a MatchFrom, where the second argument
is an Array or any IEnumerable, then the alias/bound variable from the Query could be consumed
in a Match operation as a typical use case.

    public class TotalAllNumbers : Rule
    {

        public override void Define()
        {
            IEnumerable<int> numbers = null;
            int total = 0;

            When()
                .Query(() => numbers, q =>
                    q.Match<int>(n => true).Collect())
                .MatchFrom<int>(() => total, numbers.Sum(), total > 100);

            Then()
                .Do((ctx) => Console.WriteLine(numbers.ToArray().Length));
        }
    }

**Comment by linanqiu** [comment]
How's this different from the "having" clause?

**Comment by snikolayev** [comment]
The 'having' clause can add conditions to existing patterns. The idea behind this issue though is ability to create new patterns out of objects not in the engine's memory. These two capabilities are orthogonal. You could match facts in and out of rules engine's memory, and you could then attach additional conditions to either one via the 'having' clause.

**Comment by linanqiu** [comment]
I think we have this hehe.

**Comment by snikolayev** [comment]
@linanqiu yep, you nailed it with the `From` clause added to the DSL.
