### ISSUE TITLE
Support for async rules

### ISSUE THREAD

**Issue by snikolayev** [NRules/NRules#84]
Would be great if there was support for async rules. For example, if the rule needed to call out to a dependent service, which could include network I/O (e.g. a web service call), it wouldn't have to block a CPU thread while waiting for that response.

Depending on how precious backwards compatibility is to you, you could just do a major rev and change `void IRuleAction::Invoke` to become `Task IRuleAction::InvokeAsync` instead, change `ISession::Fire` to `ISession::FireAsync` and then change the implementation of `Session::Fire` to be an async method where you await the call to `IRuleAction::InvokeAsync`. Then obviously you also need to change the implementation of `RuleAction::Invoke` so that it uses async delegates under the covers, but this is all pretty straightforward.

If you didn't want to be that breaking you could be much more creative and introduce a specific `IRuleActionAsync` interface with the `InvokeAsync` method, but then you need a common base type. Would it be `IRuleAction`? That would be weird because then anyone implementing an async rule would have to implement the sync interface as well. If you don't have a common base type though, how would you be able to store/return all the diff. types of rules in a collection such as the `ICompiledRule::Actions` property? You could introduce a new interface for the common base type, `IRuleActionBase` (not my fave name) which is purely a \"marker\" interface and then have `IRuleAction` and `IRuleActionAsync` derive from that. While that would give you compile time backwards compat, I'm quite sure that is not runtime backwards compat, so all libraries would have to be recompiled anyway.

There are of course some perf benefits to not having everything be async when it's not needed (no overhead of Tasks being allocated all over the place and whatnot), but the challenge of supporting the two different interfaces in the underlying implementations, especially in the face of perfect backwards compatibility could be quite daunting. So, just some food for thought.

**Comment by AnandPalanidurai** [comment]
Can I have an example for async rules support?

**Comment by snikolayev** [comment]
@AnandPalanidurai async rules are not supported at the moment

**Comment by AnandPalanidurai** [comment]
@snikolayev  Thanks. Noted
