### ISSUE TITLE
Save and load from file

### ISSUE THREAD

**Issue by snikolayev** [NRules/NRules#85]
Does it make sense to allow the saving and loading of rules from a file (or Stream)?

**Comment by f-bourqui** [comment]
It make sense, we already use an xml file to save and load our rules into a running server in production. This dynamically change the behavior of our system when the client requires it. 

For now we use an xml language very specific to our use, it is not generic at all and does not correspond to any standard rule language for interoperability.

A generic way to save and load rules on live would be very welcome.

**Comment by SuheylZ** [comment]
@SmartLibertyFBO  I'm interested in knowing how are you managing the stuff in file because the rules are declarative. Are you creating some assembly at run-time to add the rules to it?

**Comment by f-bourqui** [comment]
@MercedeX I'm using the [Rule-Builder](https://github.com/NRules/NRules/wiki/Rule-Builder) and built something like this:
(Fichier XML= XML File)
![image](https://cloud.githubusercontent.com/assets/11056872/23991066/5cfccea2-0a38-11e7-9cb1-dba619c8a8eb.png)
**SmartRule** can be created by **XMLRule** or generate **XMLRule**. The build operation is using **RuleBuilder** to create an **IRuleDefinition** (NRules interface).

When rules change, we recreate the session factory with new rules.


For a more generic way, maybe we should consider implementing [RuleML](http://wiki.ruleml.org/index.php/RuleML_Home)

**Comment by kotpal** [comment]
We need to save as text and load as text (since we want to store/retrieve the rules from the database). What are your plans and status on this please?

**Comment by snikolayev** [comment]
@kotpal at present, if you need to express rules in a form other than built-in C# DSL, you'd need to write an adapter that would translate them into IRuleDefinition using [Rule Builder](https://github.com/NRules/NRules/wiki/Rule-Builder). There is an example project under "samples" that shows how to do it.
Writing general purpose serializer for expression trees is actually fairly complicated, and is not high on my list at this time.

**Comment by sureshsakthivel** [comment]
> It make sense, we already use an xml file to save and load our rules into a running server in production. This dynamically change the behavior of our system when the client requires it.
> 
> For now we use an xml language very specific to our use, it is not generic at all and does not correspond to any standard rule language for interoperability.
> 
> A generic way to save and load rules on live would be very welcome.

Hi , 
Please let me know how to save the rules into XML.

Regards
SureZ

**Comment by snikolayev** [comment]
Implemented by adding support to serialized rules to/from JSON. See #284
